package com.pieronex.smartcontact;

import android.app.Activity;
import android.content.ContentResolver;
import android.database.Cursor;
import android.os.Parcel;
import android.os.Parcelable;
import android.provider.ContactsContract;
import android.util.Log;

import java.util.ArrayList;
import java.util.List;

/**
 * <h1>Account</h1>
 * This class consists of attributes of each individual account in the contacts along with getters and setters.
 *
 *
 * @author Puriwat Khantiviriya
 * @author Sasawat Chanate
 * @author Thitiwat Watanajaturaporn
 * @version 1.0
 * @since   2014-11-25
 */


public class Account extends  Activity implements Parcelable{//extends Observable{
    private String displayName = "";//name
    private String phoneNo = "";//phone number
    private String email = "";//e-mail
    private String nickName = "";
    private String organization;//organization
    private String id= "";//id
    private String tags ="";
    private ContentResolver contentResolver;//

    /**
     * Constructor for receiving account's information
     *
     *
     * @param  mDisplayName the account's full name
     * @param  mPhoneNo the account's phone number
     * @param  mEmail the account's email
     * @param  mNickName the account's nickname
     * @param  mTag the account's tag
     * @param  mId the account's id (phone autogenerated)
     * @param  mContentResolver provides application access to the content model
     */
//mGivenName, mPhoneNo, mEmail,mNickname, mTag, mId, contentResolver)
    public Account(String mDisplayName, String mPhoneNo, String mEmail, String mNickName, String mTag, String mId, ContentResolver mContentResolver){
        displayName = mDisplayName;
        phoneNo = mPhoneNo;
        nickName = mNickName;
        tags = mTag;
        id = mId;
        email = mEmail;
        contentResolver = mContentResolver;
    }


//    public Account(String mFirstName, String mPhoneNo, String mId, ContentResolver mcontentResolver){
//
//        this(mFirstName, mPhoneNo, null, null, null , mId, mcontentResolver);
//    }

    public String getDisplayName() {
        return displayName;
    }

    public String getPhoneNo() {
        return phoneNo;
    }

    public String getTags() {
        return tags;
    }

    public void setTags(String mTags1){
        this.tags = mTags1;
    }


    public List<String> getEmail(ContentResolver mContenResolver){
        ArrayList<String> emails = new ArrayList<String>();
        Cursor emailCur = contentResolver.query(
                ContactsContract.CommonDataKinds.Email.CONTENT_URI,
                null,
                ContactsContract.CommonDataKinds.Email.CONTACT_ID + " = ?",
                new String[]{this.getId()}, null);

        while (emailCur.moveToNext()) {
            // This would allow you get several email addresses
            // if the email addresses were stored in an array
            String mEmail = emailCur.getString(
                    emailCur.getColumnIndex(ContactsContract.CommonDataKinds.Email.DATA));
            emails.add(mEmail);

        }
        emailCur.close();
        return emails;
    }




    public void setDisplayName(String displayName) {
        this.displayName = displayName;
    }

    public void setPhoneNo(String phoneNo) {
        this.phoneNo = phoneNo;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getNickName(){
        return nickName;
    }

    public void setNickName(String mNickName){
        this.nickName = mNickName;
    }

    public String toString(){
        return displayName +"\n\t"+ "Tel. " + phoneNo + "\n";
    }


    /**
     * Constructor for receive Object in Parcel data type
     *
     *
     * @param  in the input parcel
     */
    public Account(Parcel in){
        String[] data = new String[6];
        in.readStringArray(data);
        /*set "displayName" to data[0];*/
        setDisplayName(data[0]); //displayName = data[0];
        /*set "phoneNo" to data[1];*/
        setPhoneNo(data[1]);
        /*email = data[2];*/
        setEmail(data[2]);
        /*address = data[3];*/
        setNickName(data[3]);
        /*organization =data[4];*/
         setTags(data[4]);
        /*id = data[5];*/
        setId (data[5]);
    }


    ////////////////////////////////////////////////////////////
    ///* This below part is for making Account as Parcelable  */
    ///* So that Intent can send an Object through parameter  */
    ////////////////////////////////////////////////////////////
    @Override
    public int describeContents() {
        return 0;
    }

    @Override
    public void writeToParcel(Parcel dest, int flags) {
        dest.writeStringArray(new String[]{displayName, phoneNo, email, nickName, tags, id});
    }

    public static final Parcelable.Creator CREATOR = new Parcelable.Creator() {
        public Account createFromParcel(Parcel in) {
            return new Account(in);
        }

        public Account[] newArray(int size) {
            return new Account[size];
        }
    };

}
